safe: true
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'serve.sh', 'article.png', 'LICENSE']
baseurl: /MThesis
imports:
    - https://peerj.github.io/research-article/research-article.html
theme: https://peerj.github.io/paper-themes/paper-now/
